---
# See sample alacritty.yml with all possible values at https://github.com/alacritty/alacritty/releases
live_config_reload: true

window:
  decorations: buttonless

font:
  size: 18.0
  normal:
    family: Essential PragmataPro
    style: Regular

scrolling:
  history: 0

url:
  launcher: None
colors:
  name: Erebus
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    style:
      shape: Block
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#757575"
    red: "#ff5f5f"
    green: "#de8a36"
    yellow: "#d78787"
    blue: "#af5fd7"
    magenta: "#ff87d7"
    cyan: "#dea3e5"
    white: "#b8b8b8"
  bright:
    black: "#b8b8b8"
    red: "#d78787"
    green: "#ff9f6f"
    yellow: "#ff5f5f"
    blue: "#dea3e5"
    magenta: "#d7afaf"
    cyan: "#af5fd7"
    white: "#757575"
