repos:
- repo: local
  hooks:
  - id: jsonlint
    name: jsonlint
    language: system
    entry: .venv/bin/python scripts/jsonlint.py
    pass_filenames: false
    always_run: true
  - id: shellcheck
    name: shellcheck
    language: system
    entry: .venv/bin/python scripts/shellcheck.py
    pass_filenames: false
    always_run: true
